title: "Battle of the Water Futures ðŸš°"
description: Battle of the Water Futures website for general information, updates, and documentation.
baseurl: "/water-futures-battle"
url: "https://waterfutures.github.io/"

# Theme
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 2..3
  auto_ids: true
  parse_block_html: true
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false

# Navigation
navigation:
  - title: Home
    url: /
  - title: Participate
    url: /participating.html
  - title: Motivation
    url: /motivation.html
  - title: The BWF Problem
    url: /problem/
    subnav:
      - title: System Description
        url: /problem/system-description/
        subnav:
          - title: Water Utilities
            url: /problem/system-description/water-utilities.html
          - title: Municipalities
            url: /problem/system-description/municipalities.html
          - title: Sources
            url: /problem/system-description/sources.html
          - title: Pumping Stations
            url: /problem/system-description/pumping-stations.html
          - title: Pipes
            url: /problem/system-description/pipes.html
      - title: External Drivers
        url: /problem/external-drivers/
        subnav:
          - title: Climate
            url: /problem/external-drivers/climate.html
          - title: Energy System
            url: /problem/external-drivers/energy-system.html
          - title: Economy and Financing
            url: /problem/external-drivers/economy-financing.html
      - title: System Interventions
        url: /problem/system-interventions/
      - title: System Requirements
        url: /problem/system-requirements/
  - title: Team
    url: /team.html
  - title: Contact Us
    url: /contact.html
  - title: Changelog
    url: /changelog.html

# Exclude files from processing
exclude:
  - 'problem/*.md'
  - motivation.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - trash
  - paper
  - bin