title: "Battle of the Water Futures ðŸš°"
description: Battle of the Water Futures website for general information, updates, and documentation.
baseurl: "/water-futures-battle"
url: "https://waterfutures.github.io/"

# Theme
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 2..3
  auto_ids: true

# Navigation
navigation:
  - title: "Home"
    url: /
  # - title: Motivation
  #   url: /motivation
  - title: Participate
    url: /participating
  # - title: Problem Description
  #   url: /problem/
    # subnav:
    #   - title: Network & Options
    #     url: /problem/network-options
    #   - title: Input Data & Scenarios
    #     url: /problem/scenarios
    #   - title: Evaluation Metrics
    #     url: /problem/metrics
  - title: Team
    url: /team
  - title: Contact Us
    url: /contact

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor