title: "Battle of the Water Futures ðŸš°"
description: Battle of the Water Futures website for general information, updates, and documentation.
baseurl: "/water-futures-battle"
url: "https://waterfutures.github.io/"

# Theme
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 2..3
  auto_ids: true

# Navigation
navigation:
  - title: Home
    url: /
  - title: Motivation
    url: /motivation.html
  - title: Participate
    url: /participating.html
  - title: The BWF Problem
    url: /problem/
    subnav:
      - title: System Description
        url: /problem/system-description/
        subnav:
          - title: Water Utilities
            url: /problem/system-description/water-utilities.html
          - title: Municipalities
            url: /problem/system-description/municipalities/
            subnav:
            - title: Water Demand Model
              url: /problem/system-description/municipalities/water-demand.html
            - title: Non Revenue Water Model
              url: /problem/system-description/municipalities/nrw.html
          - title: Sources
            url: /problem/system-description/sources.html
          - title: Pumping Stations
            url: /problem/system-description/pumping-stations.html
          - title: Pipes
            url: /problem/system-description/pipes.html
      - title: System Requirements
        url: /problem/system-requirements/
      - title: System Interventions
        url: /problem/system-interventions/     
      - title: External Drivers
        url: /problem/external-drivers/
        subnav:
          - title: Climate
            url: /problem/external-drivers/climate.html
          - title: Energy System
            url: /problem/external-drivers/energy-system.html
          - title: Economy and Financing
            url: /problem/external-drivers/economy-financing.html
  - title: Team
    url: /team.html
  - title: Contact Us
    url: /contact.html

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - trash
  - paper
  - bin